grasp_planning_node:
  ros__parameters:
    grasp_output_service: "grasp_requests"
    table_to_camera_height: 0.65
    easy_perception_deployment:
      epd_enabled: false
      tracking_enabled: true
      epd_topic: "/processor/epd_localize_output"
      epd_service: "epd_perception_service"
    camera_parameters:
      point_cloud_topic: "/camera/pointcloud"
      camera_frame: "camera_color_optical_frame"
    point_cloud_params:
      passthrough_filter_limits_x: [-0.50, 0.50]
      passthrough_filter_limits_y: [-0.15, 0.10]
      passthrough_filter_limits_z: [0.01, 0.70]  
      segmentation_max_iterations: 50
      segmentation_distance_threshold: 0.01
      cluster_tolerance: 0.01
      min_cluster_size: 750
      cloud_normal_radius: 0.03
      fcl_voxel_size: 0.005
      octomap_resolution: 0.01
    end_effectors:
      end_effector_names: [suction_cup]
      suction_cup:
        type: suction
        num_cups_length: 1
        num_cups_breadth: 1
        dist_between_cups_length: 0.06
        dist_between_cups_breadth: 0.06
        cup_radius: 0.005
        cup_height: 0.01
        gripper_coordinate_system:
          length_direction: "x"
          breadth_direction: "y"
          grasp_approach_direction: "z"
        grasp_planning_params:
          num_sample_along_axis: 3
          search_resolution: 0.01
          search_angle_resolution: 4
          weights:
            curvature: 1.0
            grasp_distance_to_center: 1.0
            number_contact_points: 1.0
    visualization_params:
      point_cloud_visualization: false
      
