controller_names:
  - fake_ur5_arm_controller
  - fake_hand_controller
fake_ur5_arm_controller:
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
fake_hand_controller:
    joints:
      - panda_finger_joint1
      - panda_finger_joint2
initial:
   panda_arm: ready
   hand: open
