robot:
  name: ur5
  brand: universal_robot
  filepath: ""
  base_link: base_link
  ee_link: tool0
  links:
    - base_link
    - shoulder_link
    - upper_arm_link
    - forearm_link
    - wrist_1_link
    - wrist_2_link
    - wrist_3_link
    - ee_link
    - base
    - tool0
end_effector:
  name: single_suction
  brand: single_suction_gripper
  filepath: /home/rosi5/emd_ws/src/assets/end_effectors/single_suction_gripper/single_suction_description
  base_link: wrist_fixture
  robot_link: tool0
  ee_type: suction
  attributes:
    array_width: 1
    array_height: -1
  links:
    - wrist_fixture
    - suction_cup_link
objects:
  table:
    child_link: table
    links:
      table:
        visual:
          name: None
          geometry:
            filepath: /home/rosi5/emd_ws/src/assets/environment/table_description/meshes/visual/table.stl
            scale:
              scale_x: 0.001
              scale_y: 0.001
              scale_z: 0.001
          material:
            name: aluminum
            r: 0.549
            g: 0.557
            b: 0.529
            a: 1
        collision:
          name: None
          geometry:
            filepath: /home/rosi5/emd_ws/src/assets/environment/table_description/meshes/collision/table.stl
            scale:
              scale_x: 0.001
              scale_y: 0.001
              scale_z: 0.001
    table_base_joint:
      ext_joint_type: fixed
      child_link: table
external joints:
  table:
    parent object: world
    parent link: world